### ISSUE TITLE
Cannot run firestore:init

### ISSUE THREAD

**Issue by Snickdx** [gdg-x/hoverboard#1374]
**Describe the bug**
Firestore init fails, more specifically the part "babel-node ./internals/import-default-data". I keep getting an error when node attempts to import the json files. Which is weird because I have used this project last year and the year before. I suspect it might be an issue with my babel version or config.

OUTPUT

internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/workspace/devfest20/docs/default-firebase-data' imported from /workspac
e/devfest20/internals/import-default-data.js
    at finalizeResolution (internal/modules/esm/resolve.js:259:11)
    at moduleResolve (internal/modules/esm/resolve.js:636:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:726:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hoverboard@3.0.0 firestore:init: `firebase firestore:delete -r --all-collections -y && firebase functions:config:set schedule.enabled=true && firebase deploy --except hosting && babel-node ./internals/import-default-data`

**To Reproduce**
Follow the usual steps to set up project, firebase project, login, add config, service account etc
run "npm run firestore:init"

**Expected behavior**
Firestore data imports

**Desktop (please complete the following information):**

- OS: Windows and Ubuntu

**Additional context**
Used to work last year and the year before

**Comment by zptoth** [comment]
I am experiencing the same issue.

**Comment by abraham** [comment]
Sorry about that. Babel was removed with some earlier work but those scripts had not been updated. I just updated those to ts-node so `npm run firestore:init` should work now.

**Comment by zptoth** [comment]
Thanks. It's getting better but still won't init. 
See log here: https://github.com/gdg-x/hoverboard/issues/1373#issuecomment-702404248

**Comment by zptoth** [comment]
Looks like it's OK now.
See here: https://github.com/gdg-x/hoverboard/issues/1373#issuecomment-702752711
Thanks for your support!

**Comment by Snickdx** [comment]
Thanks! It works now!
