### ISSUE TITLE
v2 doesn't work on Safari

### ISSUE THREAD

**Issue by MrCsabaToth** [gdg-x/hoverboard#317]
I don't know how much it's known. Unfortunately I don't have a Mac. I tried to debug an iPad remotely with `weinre` but I didn't see anything on the console so I have no idea why it doesn't work. By not working I mean that it only displays the site title on white background. It's true not only for my own derivative, but for https://hoverboard-v2-dev.firebaseapp.com/ too.

**Comment by ozasadnyy** [comment]
Are you using the latest version? Safari was fixed in #300

**Comment by MrCsabaToth** [comment]
My fork is not 100% up-to-date but I have the #300 merged. https://hoverboard-v2-dev.firebaseapp.com/  is not functional on Safari, does that have #300?

**Comment by ozasadnyy** [comment]
Probably not, I have to update travis configs. Will take a look today

**Comment by MrCsabaToth** [comment]
BTW, this also means that on iOS there's no way to view the website because &*$@^ Apple enforces the same engine under the browsers (I tried FF, Chrome, Safari). I don't know if the situation is the same on desktop OS X.

**Comment by MrCsabaToth** [comment]
I got a Safari console snapshot from @riowaller:

`[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] SyntaxError: Unexpected token ')'
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1:455)
	global code (data:text/javascript;charset=utf-8,!fu…%0A:1:3700)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%22…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
	global code (data:text/javascript;charset=utf-8,!fu…%0A:1:776)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
	global code (data:text/javascript;charset=utf-8,!fu…%0A:1:674)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
	global code (data:text/javascript;charset=utf-8,!fu…%0A:1:3297)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1:486)
	global code (data:text/javascript;charset=utf-8,!fu…%0A:1:1118)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1:1540)
	global code (data:text/javascript;charset=utf-8,!fu…%0A:1:4084)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1:4703)
	global code (data:text/javascript;charset=utf-8,!fu…%0A:1:7451)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
	global code (data:text/javascript;charset=utf-8,!fu…%0A:1:1068)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1:177)
	global code (data:text/javascript;charset=utf-8,!fu…%0A:1:1708)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
	global code (data:text/javascript;charset=utf-8,!fu…%0A:1:5464)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1:137)
	global code (data:text/javascript;charset=utf-8,!fu…%0A:1:3309)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1)
	global code (data:text/javascript;charset=utf-8,!fu…%0A:1:3840)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,!fu…%0A:1:121)
	global code (data:text/javascript;charset=utf-8,!fu…%0A:1:2490)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function) (data:text/javascript;charset=utf-8,cla…%0A:1)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function) (data:text/javascript;charset=utf-8,con…%0A:1)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function) (data:text/javascript;charset=utf-8,con…%0A:1)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function) (data:text/javascript;charset=utf-8,con…%0A:1)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function) (data:text/javascript;charset=utf-8,con…%0A:1)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function) (data:text/javascript;charset=utf-8,con…%0A:1)
[Error] ReferenceError: Can't find variable: ReduxMixin
	global code (data:text/javascript;charset=utf-8,cla…%0A:1)
[Error] ReferenceError: Can't find variable: UtilsFunctions
	global code (data:text/javascript;charset=utf-8,cla…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] ReferenceError: Can't find variable: ReduxMixin
	global code (data:text/javascript;charset=utf-8,cla…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function) (data:text/javascript;charset=utf-8,con…%0A:1)
[Error] ReferenceError: Can't find variable: ShareMixin
	global code (data:text/javascript;charset=utf-8,cla…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,cla…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,cla…%0A:1)
[Error] ReferenceError: Can't find variable: ScrollFunctions
	global code (data:text/javascript;charset=utf-8,cla…%0A:1)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function) (data:text/javascript;charset=utf-8,Pol…%0A:1)
[Error] SyntaxError: Unexpected token ')'
	(anonymous function) (data:text/javascript;charset=utf-8,cla…%0A:1)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function) (data:text/javascript;charset=utf-8,cla…%0A:1)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%22…%0A:1)`

**Comment by MrCsabaToth** [comment]
So seems like Safari is not OK with some newer JS features (let, const), and the Polymer polyfill doesn't come across somehow? Just guessing.

**Comment by ozasadnyy** [comment]
@MrCsabaToth I confirm it's not working in Safari. I don't think it's a problem with ES6 as it has good support https://kangax.github.io/compat-table/es6/. Should be something with the code. Looking to it.
P.S. The latest version is deployed https://hoverboard-v2-dev.firebaseapp.com/

**Comment by ozasadnyy** [comment]
@MrCsabaToth I have pushed a quick fix (disable uglify) until I will find the solution

**Comment by MrCsabaToth** [comment]
Wow, it could be the minification/uglification? The https://hoverboard-v2-dev.firebaseapp.com/ still doesn't work on iOS (trying a 3rd gen iPad with iOS 9.3)

**Comment by MrCsabaToth** [comment]
Got a console log from @riowaller about the latest which supposedly not uglified:

[Warning] 20 console messages are not shown.
[Error] SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
	(anonymous function)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function)
[Error] SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
	(anonymous function)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function)
[Error] SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
	(anonymous function)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function)
[Error] SyntaxError: Unexpected token ')'
	(anonymous function)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function)
[Error] SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
	(anonymous function)
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:3)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:14)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:2)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:89)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:6)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:3)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:20)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:6)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:2)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:2)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:2)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:3)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:2)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,%0A…%0A:38)
	global code (data:text/javascript;charset=utf-8,%0A…%0A:353)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:4)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,%0A…%0A:13)
	global code (data:text/javascript;charset=utf-8,%0A…%0A:102)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,%0A…%0A:5)
	global code (data:text/javascript;charset=utf-8,%0A…%0A:124)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,%0A…%0A:5)
	global code (data:text/javascript;charset=utf-8,%0A…%0A:328)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:7)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:5)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:3)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:2)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:5)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:63)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,%0A…%0A:59)
	global code (data:text/javascript;charset=utf-8,%0A…%0A:153)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:3)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,%0A…%0A:260)
	global code (data:text/javascript;charset=utf-8,%0A…%0A:486)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:7)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:7)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,%0A…%0A:290)
	global code (data:text/javascript;charset=utf-8,%0A…%0A:614)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:11)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:7)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:2)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:48)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,%0A…%0A:5)
	global code (data:text/javascript;charset=utf-8,%0A…%0A:109)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:8)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,%0A…%0A:9)
	global code (data:text/javascript;charset=utf-8,%0A…%0A:206)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,%0A…%0A:6)
	global code (data:text/javascript;charset=utf-8,%0A…%0A:620)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:8)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:8)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,%0A…%0A:40)
	global code (data:text/javascript;charset=utf-8,%0A…%0A:361)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,%0A…%0A:5)
	global code (data:text/javascript;charset=utf-8,%0A…%0A:282)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:7)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:3)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:3)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:2)
[Error] ReferenceError: Can't find variable: Polymer
	(anonymous function) (data:text/javascript;charset=utf-8,%0A…%0A:10)
	global code (data:text/javascript;charset=utf-8,%0A…%0A:345)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:3)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:2)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:9)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:8)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:37)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:2)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:2)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:2)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function)
[Error] ReferenceError: Can't find variable: ReduxMixin
	global code (data:text/javascript;charset=utf-8,%0A…%0A:3)
[Error] ReferenceError: Can't find variable: UtilsFunctions
	global code (data:text/javascript;charset=utf-8,%0A…%0A:3)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:2)
[Error] ReferenceError: Can't find variable: ReduxMixin
	global code (data:text/javascript;charset=utf-8,%0A…%0A:3)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:2)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function)
[Error] ReferenceError: Can't find variable: ShareMixin
	global code (data:text/javascript;charset=utf-8,%0A…%0A:3)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:3)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:3)
[Error] ReferenceError: Can't find variable: ScrollFunctions
	global code (data:text/javascript;charset=utf-8,%0A…%0A:3)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function)
[Error] SyntaxError: Unexpected token ')'
	(anonymous function)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function)
[Error] ReferenceError: Can't find variable: Polymer
	global code (data:text/javascript;charset=utf-8,%0A…%0A:4)

**Comment by cliveb** [comment]
@MrCsabaToth Curious what polymer-cli version are you using tin your build?

**Comment by MrCsabaToth** [comment]
@cliveb Maybe that's the problem? It is `0.17.0`, I'm upgrading now to the recent `1.5.4` and see if it helps. This fell off of my radar

**Comment by cliveb** [comment]
@MrCsabaToth I had a hunch. I will try last yrs Hoverboard V1.2.0 with Polymer 0.17.0  (Kill 2 birds w/ on stone please).

**Comment by MrCsabaToth** [comment]
Trying to upgrade to `polymer-cli` `1.5.4` on Ubuntu 17.04:

> wd@1.4.1 install /usr/local/lib/node_modules/polymer-cli/node_modules/wd
> node scripts/build-browser-scripts

/usr/local/lib/node_modules/polymer-cli/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/polymer-cli/node_modules/wd/build'
    at Object.fs.mkdirSync (fs.js:877:18)
    at sync (/usr/local/lib/node_modules/polymer-cli/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/wd/scripts/build-browser-scripts.js:6:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wd@1.4.1 install: `node scripts/build-browser-scripts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wd@1.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/csaba/.npm/_logs/2017-09-19T02_39_42_130Z-debug.log

**Comment by MrCsabaToth** [comment]
All right: https://github.com/Polymer/polymer-cli/issues/828

**Comment by cliveb** [comment]
@MrCsabaToth The EACCES issue, I've seen on my new Macbook. I solved by re-installing npm in the Hoverboard base folder (I think). Or may be the older version of polymer left some crap behind...

npm install  
npm build

**Comment by MrCsabaToth** [comment]
I also upgraded `firebase-cli` from `3.10.1` to `3.12.0`. I'm on Linux and will take some time to access an iOS device to try if it worked.

@cliveb I had similar EACCESS error with some dependency package of `firebase-cli`, `--unssafe-perm` solves it. In terms of versions I'm feeing ahead of the front line right now: https://pbs.twimg.com/media/CHKb0FSUwAIZqy5.jpg
:)

**Comment by cliveb** [comment]
@MrCsabaToth Polymer 0.17.0 completes with:  

Update available 5.3.0 → 5.4.2    │
   │     Run npm i -g npm to update

**Comment by MrCsabaToth** [comment]
@cliveb which package `5.3.0 → 5.4.2`? I have now `1.5.4` and my Mac tester reported that it worked

the site is up with iOS and OS X as well now: https://valleydevfest.com

**Comment by MrCsabaToth** [comment]
So this was only a problem with my local environment. BTW with `hoverboard-v2` due to a `nodejs` bug and the fact that we use functions and messaging, you either have to use newer node than `8.0` (I had to fast forward from the 17.04 Ubuntu's official repo using `nvm` to `8.1.0` node. Or you have to stick with 6.x node.

**Comment by MrCsabaToth** [comment]
@ozasadnyy I think we can close this.

**Comment by cliveb** [comment]
@MrCsabaToth  Polymer install completed with a box recommending npm 5.3.0 --> 5.4.2.

https://valleydevfest.com looks awesome. Please confirm your polymer --version is?

**Comment by MrCsabaToth** [comment]
polymer --version `1.5.4`
npm --version `5.0.3`

**Comment by MrCsabaToth** [comment]
@ozasadnyy Oh, and the `uglify` can be put back to the `gulp`. I'm building and have it tested that way.

**Comment by ozasadnyy** [comment]
Guys, sorry to be late here. `polymer-cli` should not effect Hoverboard v2 as it's using custom build with `polymer-build` defined in `package.json`.
@MrCsabaToth so you have tried to build with `uglify` and it works on Safari?

**Comment by MrCsabaToth** [comment]
@ozasadnyy polymer-cli version seemed like affecting the build in my case. I haven't got back words yet if the uglify works, but my build is currently including uglify so it can be tested.

**Comment by MrCsabaToth** [comment]
I suspect that the iPad with the iOS 9.3 may have Safari which doesn't comply with high enough ECMAScript version we transpile to. Is there a single point where I could specify ECMAScript version?

**Comment by Splaktar** [comment]
Yes, iOS 9 lacks a lot of modern web features. iOS 10 works much better. However, there are still many users and DevFest attendees who will be running iOS 9 or Safari 9.

**Comment by ozasadnyy** [comment]
@MrCsabaToth, @Splaktar can you check in Google Analytics how many people are still using old browsers? This template is oriented for tech conferences with the assumption that most of the users are using latest versions of browsers

**Comment by MrCsabaToth** [comment]
@ozasadnyy I'm not able to collect GA data for the 9.3.x iOS devices, because the device doesn't even get to the point to ping GA. So it's hard to tell the representation. I haven't got a report about non functioning iPhone, but I've heard non functioning iPad. Unfortunately I didn't receive iOS version info (or even device generation number) for those occasions so far (non technical people).

https://valleydevfest.com
![screenshot_2017-09-28_11-41-00](https://user-images.githubusercontent.com/744949/30984575-8e1c919e-a442-11e7-838c-22a1cc224e95.png)
![screenshot_2017-09-28_11-41-36](https://user-images.githubusercontent.com/744949/30984588-92995978-a442-11e7-927c-2d62d5518e2a.png)

In another site (I cannot name) I see GA data, and iOS 9 is pretty much under represented:
![screenshot_2017-09-28_11-37-52](https://user-images.githubusercontent.com/744949/30984666-d2465db4-a442-11e7-8fbd-9c8739b4e765.png)

What I saw on IE 11 that it didn't even like the new javascript String interpolation (reverse single quote). 
![d00579075bb846f38eeba37d095d038a_crop](https://user-images.githubusercontent.com/744949/30984881-8b80e3d0-a443-11e7-8640-655e9d6ba378.png)
I corrected those back ticks because in those strings there's no real interpolation going on, and that choked the browser even in the beginning. https://github.com/gdgfresno/valleydevfest2017/commit/d04298ba75a6072d91fc8b058917414c3f040e31 I haven't tested if it solves the problem at least for IE11 (which maybe just as a corner case as iOS 9.3), but it didn't help iOS 9.3.
I went further and I tried transpilation:
https://github.com/gdgfresno/valleydevfest2017/commit/82ca71034bf9ffa157cb2add8361b81deb288874
But that seemed to make things worse and make the site not function even on devices which worked before. Maybe I didn't do the transpilation correctly?

I agree that we shouldn't grind on corner cases. But I want the website to be available for as wide audience as possible, otherwise they can point at us and shame Google why it's technology doesn't work.

Thanks for your work about fixing iOS and Safari in general, that was a big help.

**Comment by MrCsabaToth** [comment]
I say if we can solve compatibility with a transpilation build step, and maybe some small changes I mention above, we should do so. Otherwise we can say it's a corner case. It's hard to tell what's the user exposure though. My primary OS is Linux, I access Windows rarely, and I cannot see any console errors when I try to remote debug an iOS iPad using `weinre` with my Linux dev box. Mac and Safari is very popular here in the us :P

**Comment by ozasadnyy** [comment]
Next weeks are pretty busy due to dfua, I will try to find a time and fix it but to be honest I can't promise that it will be fixed by this time

**Comment by MrCsabaToth** [comment]
@ozasadnyy No worries, I think this can be a corner case, other issues and features can be more important. Oh, I just realized DFUA == Ukraine DevFest. Are you rolling with v2?

**Comment by ozasadnyy** [comment]
@MrCsabaToth no, we have the conference next week and have more prioritize tasks to do

**Comment by dbs** [comment]
Started working towards transpiling to ES2015 so that IE11 will also be supported by adding the following to `polymer.json` per https://www.polymer-project.org/2.0/toolbox/build-for-production#compiling :

    "js": {"compile": true, "minify": true},

Unfortunately this triggers a build error when you run `polymer build`:

    $ polymer build
    info:    Clearing build/ directory...
    warn:    .js: Unable to optimize /home/dan/source/gdg-sudbury-devfest/src/mixins/redux-mixin.html_script_0.js 
    { err: 'unknown: Unexpected token, expected , (2:26)' }
    warn:    .js: Unable to optimize /home/dan/source/gdg-sudbury-devfest/src/mixins/redux-mixin.html_script_0.js 
    { err: 'unknown: Unexpected token, expected , (2:26)' }
      const heroSettings = {$ heroSettings | dump | safe $};
                              ~

    src/mixins/redux-mixin.html(8,26) error [parse-error] - Unexpected token heroSettings

So it looks like the {$ $} syntax (from redux?) needs some other precompile step before it gets passed to the Polymer build.

**Comment by cliveb** [comment]
@dbs make current "useBuiltIns" auto import only used + necessary polyfills per file per https://github.com/babel/babel-preset-env/pull/241

**Comment by MrCsabaToth** [comment]
@dbs What's your repo.

FYI GDG Riga will probably use Hoverboard v2 for their next year event. At least it is right now.

**Comment by dbs** [comment]
@MrCsabaToth https://github.com/dbs/gdg-sudbury-devfest/tree/sudbury-2017 running at https://devfest201.gdgsudbury.ca

**Comment by ozasadnyy** [comment]
@dbs `{$ $}` this is the syntax of [nunjucks](https://mozilla.github.io/nunjucks/). It should be replaced with data before it pass to Polymer build: https://github.com/gdg-x/hoverboard/blob/hoverboard-v2/gulpfile.js#L58
